version: '3.1'
services:
  #catapult-server:
  #  build: ./catapult-server
  #  volumes:
  #    - ./data:/

  catapult-rest:
    build: ./catapult-rest
    ports:
      - "3000:3000"
    volumes:
      - ./resources/rest/rest.json:/opt/catapult-rest/rest/resources/rest.json
    depends_on:
      - mongo
    # environment:
    #  MONGO_URL: mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
